version: 2

jobs:
  build:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -yq libssl-dev pkg-config
      - run: swift build
      - run: swift test
  push-to-docker-hub:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --update --no-cache curl jq python py-pip
            pip install --upgrade --no-cache-dir awscli botocore==1.8.42
      - run:
          name: Build Docker Image
          command: |
            docker build -t api .
            docker tag api narsail/infrtutorial:latest
            docker tag api narsail/infrtutorial:$CIRCLE_SHA1
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push narsail/infrtutorial:latest
            docker push narsail/infrtutorial:$CIRCLE_SHA1
      - persist_to_workspace:
          root: ./
          paths:
            - k8s-*.yml
  deploy-to-staging:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install dependencies
          command: apk add --update --no-cache libintl gettext openjdk7-jre
      - run:
          name: Install Kubectl
          command: gcloud components install app-engine-java kubectl
      - run:
          name: Template k8s config
          command: for i in /tmp/workspace/k8s-*.yml; do envsubst < "$i" > $(basename "$i"); done
      - run:
          name: Deploy to staging
          command: |
            echo "$GOOGLE_KEY" > key.json # Google Cloud service account key
            gcloud auth activate-service-account --key-file key.json
            gcloud config set compute/zone us-central1-a
            gcloud config set project infrtutorial
            gcloud container clusters get-credentials infrtutorial

            kubectl apply -f k8s-deployment.yml
            kubectl rollout status deployment/infrtutorial

workflows:
  version: 2
  tests:
    jobs:
      - build
      - push-to-docker-hub:
          requires:
            - build
          context: dockerhub
          filters:
            branches:
              only: master
      - deploy-to-staging:
          requires:
            - push-to-docker-hub
          context: k8s
          filters:
            branches:
              only: master
